name: mapane
description: Votre application d aide au deplacement urbain

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundÃ¹leShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  get_it: ^4.0.4
  dio: ^3.0.10
  shared_preferences: ^0.5.10
  permission_handler: ^5.0.1+1
  google_maps_flutter: ^1.0.6
  flutter_svg: ^0.19.0
  provider: ^4.3.2+2
  dartz: ^0.9.2
  location: ^3.2.4
  flutter_polyline_points: ^0.2.4
  splashscreen: ^1.3.5
  walkthrough: ^0.0.3
  mobile_number: ^1.0.3
  phone_number: ^0.8.1
  cool_alert: ^1.0.3
  intl_phone_number_input: ^0.6.0
  flutter_skeleton: ^0.1.0+1
  skeleton_text: ^1.0.0
  modal_bottom_sheet: ^1.0.0+1
  flutter_switch: ^0.2.0
  simple_moment: ^1.0.7
  flutter_tindercard: ^0.2.0
  flutter_spinkit: ^4.1.2
  flutter_tts: ^2.1.0
  data_connection_checker: ^0.3.4
  bot_toast: ^3.0.5
  geodesy: ^0.3.2
  path_provider: ^1.6.27
  audioplayer: 0.8.1
  audioplayer_web: 0.7.1
  quiver:
  geolocator: ^6.2.1
  vector_math: any
  select_form_field: ^1.1.0
  firebase_messaging: ^7.0.3
  screen: ^0.0.5
  url_launcher: ^5.7.10



dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.Q<A
  uses-material-design: true
  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFLutterApp.ttf
    - family: ProfileFont
      fonts:
        - asset: assets/fonts/ProfileFont.ttf
    - family: Map
      fonts:
        - asset: assets/fonts/Map.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/markers/
    - assets/markers/mapmarker/
    - assets/markers/mapmarker/oldmarkers/
    - assets/images/new-icon-alerts/test/
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
